### ISSUE TITLE
Keyboard issues (round 2)

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/ionic#12042]
- [ ] setFocus programmatically make screen jump https://github.com/ionic-team/ionic/issues/10257
- [ ] add common test for textarea + improve test suite to cover ngModelChange 
 https://github.com/ionic-team/ionic/issues/9434
- [x] tabIndex duplicated https://github.com/ionic-team/ionic/issues/7178 (fix: https://github.com/ionic-team/ionic/pull/12043 )
- [ ] ion-input inside slider https://github.com/ionic-team/ionic/issues/10183
- [x] alert padding when it has text-inputs https://github.com/ionic-team/ionic/issues/10187 (fix: new keyboard plugin)

**Comment by gregd** [comment]
The "big keyboard/input refactor" commit closed #7047 "Auto hide tabs when keyboard is open". To enable the fix I set keyboardResizes to true in the app config. However the tabs are still visible (on Android) when keyboard is open. 

I tried to analyse the new platform/keyboard.ts code I found that the keyboardResizes===true adds listeners to keyboardWillShow, keyboardWillHide, keyboardDidShow and keyboardDidHide events. I cannot find that events in ionic-plugin-keyboard in Android code. So I guess the fix of #7047 works only on iOS.

**Comment by manucorporat** [comment]
You should not touch `keyboardResizes`, in order to fix it, native assistance is required. We will release a new keyboard plugin.

**Comment by kamilpatyk** [comment]
I have:
```
"cordova-plugin-keyboard": "^1.1.5",
"cordova-android": "^6.2.3",
```
but tabs still are visible when keyboard is active - what else should I do?

**Comment by tobiasmuecksch** [comment]
@manucorporat I'm experiencing issues with a chat like app.

- What about this WKWeb fix ?
https://github.com/ionic-team/ionic/issues/11501

- What keyboard plugin-in are we expected to use? The Ionic-Team offers two plugins.

- What is the current state on all the keyboard issues? No official team member answered any of the issues in both repos.

**Comment by kitkimwong** [comment]
@manucorporat  any update?

**Comment by Jatapiaro** [comment]
If your problem is on android, thiw will help you. In the ionic config.xml, add the following lines in the platform name="android" tag.

    <platform name="android"> 
      <edit-config file="AndroidManifest.xml" mode="merge"    target="/manifest/application/activity"> <activity android:windowSoftInputMode="adjustPan" /></edit-config>
      ...the rest of the android configs...
    </platform>

This will prevent the keyboard to push up everything and simple overlay the keyboard on the content. So the behaviour will be the same or similar to the ios keyboard

**Comment by antoine92190** [comment]
@Jatapiaro Your solution is not working for me.

I get the following error when trying to build the app `../platforms/android/res/xml/config.xml:139: AAPT: Error parsing XML: unbound prefix`

**Comment by youssmak** [comment]
On android, when the keyboard is open, the tabbar is superimposed with the navbar. 

```
/* style of the tabbar element when keyboard is open */
element.style {
    top: 0px;
}
```
Temporary fix 
```
  ngAfterViewInit() {
    let tabbarEl = <HTMLElement> (document.getElementsByClassName('tabbar')[0]);
    this.onKeyboardShowSubscription = Keyboard.onKeyboardShow()
      .subscribe(() => {
        if (this.platform.is('android') && this.platform.is('cordova') && tabbarEl) {
          setTimeout(() => tabbarEl.style.top = '48px', 100); // avoid superposition of tabbar and navbar
        }
      });
  }
```

**Comment by raessafathulalim** [comment]
have same issue here.
`cli packages: (/usr/local/lib/node_modules)
@ionic/cli-utils : 1.19.0
ionic (Ionic CLI) : 3.19.0
global packages:
cordova (Cordova CLI) : 7.1.0 
local packages:
@ionic/app-scripts : 3.1.4-201711302144
Cordova Platforms : android 6.3.0
Ionic Framework : ionic-angular 3.9.2
System:
Node : v6.11.4
npm : 3.10.10 
OS : OS X El Capitan
Xcode : Xcode 8.2.1 Build version 8C1002`

i have try with this but not working

[https://gist.github.com/EvanWillms/8773f8cfa12f469fabf0bdd7a75723e7](https://gist.github.com/EvanWillms/8773f8cfa12f469fabf0bdd7a75723e7)

`config: {
    // These options are available in ionic-angular@2.0.0-beta.2 and up.
    scrollAssist: false,    // Valid options appear to be [true, false]
    autoFocusAssist: false  // Valid options appear to be ['instant', 'delay', false]
  } // http://ionicframework.com/docs/v2/api/config/Config/`

is not supported with ionic 3 i guess
