### ISSUE TITLE
Ionic 4 RC bugs and missing breaking changes / docs

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic#16819]
This issue is to collect and keep track of bugs and missing breaking changes / documentation in the Ionic `4.0.0-rc.0` version so we can make sure to properly update and fix them.

## Bugs

- [x] Segment indicator not showing (#16820)
- [x] Interface options aren't passing mode (#16825)
- [x] Action sheet buttons shrink on press iOS (#16790)
- [x] Input Highlighting not working in Angular (#16052) (PR #17175)
- [x] FAB hidden behind toolbar - Chrome only (#16780) (PR #17048)

## Undocumented Breaking Changes

Anything missing from the following document: https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md

PR: #17214
- [x] Prefixed component classes (**Ion**)
- [x] Document how to get detail in event handlers (ionic-team/ionic-docs#258)
- [x] Update grid documentation to include the sizes of the `col` attribute (`auto` specifically)
- [x] `dismissOnPageChange` doesn't show a good alternative usage (breaking changes doc) https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#property-removed-1
- [x] Loading is still listing `dismissOnPageChange` in its docs (PR: #17357) 

## Documentation 

- [x] Reorder documentation is incomplete (ionic-team/ionic-docs#160) (PR: #17417)

**Comment by bitflower** [comment]
Still applies in beta-19 and rc0

**Comment by jonmikelm** [comment]
We haven't been able to make input error highlighting work with any of the beta releases. And it keeps failing with rc.0.

https://github.com/ionic-team/ionic/issues/16052

Form error highlight is a really common use case in any app. This bug should be addressed before going stable.

**Comment by goelectricstations** [comment]
https://beta.ionicframework.com/docs/api/tabs

<ion-tab tab="home">Home Content</ion-tab>
<ion-tab tab="settings">Settings Content</ion-tab>

is wrong need to be replaced with the equivalent

**Comment by paulstelzer** [comment]
@goelectricstations keep in mind that the docs are for `@ionic/core` and there the mentioned code is correct (there you can use ion-tab).  You are using `@ionic/angular`, so you have to keep in mind the angular integration -> https://beta.ionicframework.com/docs/api/tabs/#angular-router-integration

**Comment by goelectricstations** [comment]
@paulstelzer thanks, but I am not use angular-router-integration, I want to use @ionic/core, how you know I am using @ionic/angular? Thanks in advance

**Comment by paulstelzer** [comment]
@goelectricstations your last issue was about `@ionic/angular` -> https://github.com/ionic-team/ionic/issues/16796 - So i just want to tell you that there are differences if you use this or plain javascript ;)

**Comment by paulstelzer** [comment]
@goelectricstations  https://www.npmjs.com/package/@ionic/core - if you don't want to use angular

**Comment by brandyscarney** [comment]
I'm going to lock this issue. Please create a new issue if you find a bug with RC:

- [Ionic Framework issue](https://github.com/ionic-team/ionic/issues/new/choose)
- [Ionic Documentation issue](https://github.com/ionic-team/ionic-docs/issues/new)

We will add issues to the original list.

**Comment by brandyscarney** [comment]
Removed RTL from this as it is pinned at the top already. After we update the loading breaking changes this can be closed.
