### ISSUE TITLE
4.6.x Regressions

### ISSUE THREAD

**Issue by liamdebeasi** [ionic-team/ionic#18776]
Issues that have been checked off have been resolved in Stencil or Ionic, but not yet released until the next version of Ionic is out.

Previous regressions tracker: https://github.com/ionic-team/ionic/issues/18655

- [x] AlertController (and potentially other controllers) do not return data from `.dismiss` https://github.com/ionic-team/ionic/issues/18772
- [x] `canGoBack` always returning `false` in IonRouterOutlet https://github.com/ionic-team/ionic/issues/18759
- [x] autoGrow does not reset back to original size when textarea is cleared https://github.com/ionic-team/ionic/issues/18744
- [x] ion-input's cursor jumps to the end after the first key in Safari when text is inserted https://github.com/ionic-team/ionic/issues/18757
- [x] inputs duplicating characters on non-latin language keyboards https://github.com/ionic-team/ionic/issues/18768
- [x] hardware back button import is missing https://github.com/ionic-team/ionic/issues/18792
- [x] ion-valid and other form state classes are not copied to the parent ion-item https://github.com/ionic-team/ionic/issues/18800
- [x] datetime picker-opt-disabled class not being applied to options https://github.com/ionic-team/ionic/issues/18793
- [x] ion-card in virtual scroll causes rendering issues and large gaps to appear https://github.com/ionic-team/ionic/issues/18789 https://github.com/ionic-team/ionic/issues/18870
- [ ] Swipe to go back is activating when menu should open https://github.com/ionic-team/ionic/issues/18879

----------------------------------------------------------------

### Reporting a Regression

If you are running into a bug that worked in `4.5.0` but is not working in `4.6.x` and is not in the list above _and_ not in the [previous regression issue thread](https://github.com/ionic-team/ionic/issues/18655) please [create a new issue](https://github.com/ionic-team/ionic/issues/new/choose):
- Fill out the provided template with steps for us to reproduce
- Provide the minimal amount of code needed to reproduce the issue in a starter
- Or provide a simple code repository that only highlights the bug

Please tag @ionic-team/framework *on the issue* to bring it to our attention.

**Comment by maxtacco** [comment]
Hi @liamdebeasi , I think https://github.com/ionic-team/ionic/issues/18757 was introduced in 4.6.x. I wasn't able to reproduce it with 4.5.0.

**Comment by manucorporat** [comment]
https://github.com/ionic-team/ionic/issues/18800 also a regressions

**Comment by ppjjzz** [comment]
#18793 also a regressions

**Comment by ippeiukai** [comment]
> #18793 also a regressions

@ppjjzz If it’s not working with 4.5, let’s leave this out of 4.6 regressions.
 (Though one can argue it is more severe, there are many of us already using 4.5 and waiting/working for 4.6.x update that is as good as 4.5.)

**Comment by ppjjzz** [comment]
> > #18793 also a regressions
> 
> @ppjjzz If it’s not working with 4.5, let’s leave it out of 4.6 regressions.
> (Though one can argue it is more severe, there are many of us already using 4.5 and waiting/working for 4.6.x update that is as good as 4.5.)

It's working with 4.5 but not working at 4.6.x

**Comment by ippeiukai** [comment]
> It's working with 4.5 but not working at 4.6.x

Oh, my apologies. It read as if the bug was there since 4.1.
Perhaps better clarify the fact it is working with 4.5 in the issue?

**Comment by mbaric1** [comment]
Seems that this was working with 4.5 and it's not working with 4.6.x
#18789

**Comment by mbaric1** [comment]
Seems that this was working with 4.5 and it's not working with 4.6.x
#18789

**Comment by brandyscarney** [comment]
Closing this since we have had no further issues come in and #18879 is open and on our project board.
